language: groovy
sudo: required
services:
  - docker
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test "$TRAVIS_TAG" != "" && test $TRAVIS_REPO_SLUG == "augi/gradle-docker-java" && ./gradlew bintrayUpload publishPlugins -Pversion="$TRAVIS_TAG" --info
